# -*- coding: utf-8 -*-
"""COP1000_Module06_TodoList

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19twvkFcN4gpIBdC5WsXIQDKbmKHWyAO6
"""

# To-Do List Manager

print("To-Do List Manager\n")

task = []

for i in range(3):
  i += 1
  new_task = input(f"Enter task {i}: ")
  task.append(new_task)

print("\n--- My To-Do list ---\n")

for i, idx in enumerate(task):
  i += 1
  print(f"{i}. {idx}")

print(f"\nTotal task: {len(task)}")