# -*- coding: utf-8 -*-
"""COP1000_Module03_DecisionTool.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rteSOT3NPTZrH6lQrG4z39-Hrc2QCqLC

Purpose
The purpose of this mini project is to combine user input, comparison operators, Boolean logic, and conditional statements into a small Python program that makes a decision.

You will create a simple activity recommendation tool based on the user's temperature and weather conditions.

Expected completion time: approximately 15 minutes

Your Task
Create a Python program that asks the user:

What is the current temperature?
Is it raining? Enter yes or no.
Your program will use the answers to recommend an activity.

Program Requirements
Your program must:

Include at least one Python comment.
Use input() to collect information from the user.
Convert the temperature to an integer or float.
Store the user's answers in meaningful variables.
Use an if statement.
Use at least one elif.
Use an else.
Use at least one Boolean operator such as and, or, or not.
Display a clear recommendation.
Run without unexplained errors.
Decision Rules
Your program should make recommendations using the following rules:

If it is raining, recommend an indoor activity.
If it is not raining and the temperature is below 60, recommend a cool-weather activity.
If it is not raining and the temperature is between 60 and 84, recommend an outdoor activity.
If it is not raining and the temperature is 85 or higher, recommend an activity appropriate for hot weather.
You may choose the actual recommendations.

For example:

What is the current temperature? 72
Is it raining? no

Recommendation: This is a good day for a walk or bike ride.
Another example:

What is the current temperature? 72
Is it raining? yes

Recommendation: Consider an indoor activity today.
Your wording does not have to match the examples exactly.
"""

# User Input Section
temp = int(input("What is the current temperature? "))
rain = input("Is it raining? ")

# Program Section
if rain == "yes":
  print("Recommendation: Today is a great day for the movies!")
elif rain != "yes" and temp < 60:
  print("Recommendation: Today is a great day for a campfire!")
elif rain != "yes" and temp >= 60 and temp <= 84:
  print("Recommendation: Today is a great day for a hike!")
else:
  print("Recommendation: Today is a great day for the beach!")