# -*- coding: utf-8 -*-
"""COP1000_Module04_GuessTheNumber

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIuBTRI0DE6k5Dm4XrjuJ86cs6smPYAf
"""

import random

secret_number = random.randint(1, 20)

user_number = int(input("Welcome to Steven's Guess the Number Program! \nI am thinking of a number between 1 and 20. \nWhat is your guess: "))

attempts = 1

while secret_number != user_number:
  #Too Low
  if secret_number > user_number:
    print("Your guess is too low")
    user_number = int(input("Guess again: "))
    attempts += 1
  #Too High
  else:
    print("Your guess is too high")
    user_number = int(input("Guess again: "))
    attempts += 1
#Just Right
print("Correct!")
print(f"You guessed the number in {attempts} attempts")