# -*- coding: utf-8 -*-
"""COP1000_Module07_ContactBook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QFrSUaG2Az6XPSOv5ZpIdDXHM3QNt93I
"""

contacts = {
    "Alex": "555-1234",
    "Jordan": "555-5678",
    "Taylor": "555-9012"
}

print("Contact Book\n\nAvailable Contacts:")

for name in contacts:
  print(name)

guess = input("\nEnter a contact name: ")

#Guess contact list check
if guess in contacts:
  print(f"\n{guess}'s phone number is {contacts[guess]}")
else:
  print("\nContact not found.")