# -*- coding: utf-8 -*-
"""COP1000_Module01_HelloPython.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_kRWr98JDjXY9KFj0xcKWNzzl4jOT1sD
"""

# short welcome message

print ("Hello, Class!")

# short intro

print ("I am excited to be here and learning something new.")

# academic or career interest

print("I have always wanted to learn more about computer program and now I have that oppurtunity.")

# hope to learn in Python

print ("I hope to be able to learn as much as I can in Python. I hear that it can be used to solve complex problems if you know what you are doing.")

# closing message

print ("Best of luck to everyone this semester!")