# -*- coding: utf-8 -*-
"""COP1000_Module05_TipCalculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGZo0fLihEve4EIj-EMo4LMYZdGjiw_9
"""



#Calculates the tip amount
def calculate_tip(bill, tip_percent):
  tip = bill * (tip_percent/100)
  return tip

#Calculates the total bill
def calculate_total(bill, tip):
  total = bill + tip
  return total

print("Tip Calculator \n")

bill = float(input("Enter the bill amount: "))
tip_percent = float(input("Enter the tip percentage: "))

tip = calculate_tip(bill, tip_percent)
total = calculate_total(bill, tip)

print(f"\nBill: ${bill:.2f}\nTip: ${tip:.2f} \nTotal: ${total:.2f}")
