# -*- coding: utf-8 -*-
"""COP1000_Module02_PersonalInformation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gFEHkHbPlLmqhr1KukhTcP3pS2C_JRtr

Your Task
Create a Python program that asks a user to enter personal information and then displays a formatted summary.

Your program must ask the user for:

First name
Last name
Age
City
Academic major or career interest
Store each answer in an appropriately named variable.

Program Requirements
Your program must:

Include at least one Python comment.
Use input() to collect information.
Store each response in a meaningful variable.
Convert the user's age to an integer using int().
Calculate how old the user will be next year.
Use f-strings to display the results.
Produce a clearly formatted personal information summary.
Run without unexplained errors.
Your program should produce output similar to:

Enter your first name: Jordan
Enter your last name: Smith
Enter your age: 20
Enter your city: Jacksonville
Enter your career interest: Cybersecurity

--- Personal Information ---

Name: Jordan Smith
Age: 20
Age Next Year: 21
City: Jacksonville
Career Interest: Cybersecurity
Your program does not have to look exactly like the example, but it must meet all of the requirements.
"""

# Personal Information Form User Input

first_name = input("Enter your First Name: ")
last_name = input("Enter your Last Name: ")
age = int(input("Enter your Age: "))
city = input("Enter your City: ")
major = input("Enter your Academic Major: ")

# Personal Information Form Output

print("\n--- Personal Information ---\n")

print(f"Name: {first_name} {last_name}")
print(f"Age: {age}")
print(f"Age Next Year: {age + 1}")
print(f"City: {city}")
print(f"Academic Major: {major}")